name: certify-core-tests-unit-8_0-win
services:

  certify-core-tests-unit-8_0:
    image: certify-core-tests-unit-8_0-win:latest
    build: ..\..\..\..\
    # environment:
    #   VSTEST_HOST_DEBUG: 1
    ports:
      - 80:80
      - 443:443
      - 9696:9696
    # entrypoint: "dotnet test Certify.Core.Tests.Unit.dll -f net8.0 --filter 'ClassName=Certify.Core.Tests.Unit.CertifyManagerAccountTests
    entrypoint: "dotnet test Certify.Core.Tests.Unit.dll -f net8.0 --filter 'Name=TestCertifyManagerGetAccountDetailsDefinedCertificateAuthorityId'"
    volumes:
      # - certifydata:C:\ProgramData\certify
      - step:C:\step_share
    depends_on:
      step-ca:
        condition: service_healthy
  
  step-ca:
    image: step-ca-win:latest
    build: .
    hostname: step-ca
    ports:
      - 9000:9000
    volumes:
      - step:C:\Users\ContainerUser\.step

volumes:
  step: {}

  # certifydata:
  #   external: true
